version: '3.9'

services:
  redis:
    image: redis:7
    container_name: chatbot_redis
    ports:
      - "6379:6379"
    networks:
      - chatbot-net

  backend:
    build:
      context: ./backend
    container_name: chatbot_backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=redis
      - FRONTEND_URL=http://localhost:4200
    volumes:
      - ./backend:/app
    command: >
      sh -c "python app/training/prepare_data.py && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - chatbot-net

  frontend:
    build:
      context: ./frontend
    container_name: chatbot_frontend
    ports:
      - "4200:4200"
    environment:
      - BACKEND_URL=http://localhost:8000
      - NG_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    command: >
      sh -c "npm install && ng serve --host 0.0.0.0"
    networks:
      - chatbot-net

networks:
  chatbot-net:
    driver: bridge
